# Synapsis` Ruby IRC Bot
# Copyright (C) 2015  Chris Tyrrel

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

adminnet: FususIRC
ownernickserv: ChasedSpade
adminchannel: "##AdminChannel"

bot:
  nickserv: UnPasswordO
  nick: Synapsis`
  user: Synapsis
  channels:
    - "#MainChannel"

servers:
  BitsJoint-IRC:
    server: lambda.atomicedge.org
    port: 6697
    channels:
      - "#Channel1"
      - "#Channel2"
      - "#Channel3"
  FususIRC:
    server: irc.fusus.org
    port: 6697
    channels:
      - "#OtherImportantChannel"
  Freenode:
    server: chat.freenode.net
    port: 6697
    channels:
      - "#OtherImportantchannel"

zncs:
  Parene:
    server: bncserver1.christyrrel.me
    port: 1339
    password: hiimafancypassword
  Dainra:
    server: bncserver2.christyrrel.me
    port: 1339
    password: hiimafancypassword
